### ISSUE TITLE
Netlify URL

### ISSUE THREAD

**Issue by ArthurVBS** [Jonas-petty/GitHub_User_Search#1]
**Cara tá muito legal a tua aplicação, a dica que eu te dou é de alterar a url do netlify.**

![image](https://user-images.githubusercontent.com/84406367/188427625-f353262b-40b0-4c79-a8ed-579d8f2c35f3.png)

Dá uma olhada nesse [link](https://www.raulmelo.dev/blog/subindo-seu-projeto-front-end-gratuitamente-netlify), lá para o final do artigo mostra como alterar a url. É isto, boa sorte ^^

![image](https://user-images.githubusercontent.com/84406367/188427782-2978f63b-505b-4e02-8f63-3fd1314ceb45.png)

**Comment by Jonas-petty** [comment]
@ArthurVBS Valeu pela dica!
